entries/forms.py
import wtforms
from wtforms.validators import DataRequired,Email,Optional,URL,Length
from models import Entry, Tag



class ImageForm(wtforms.Form):
    file = wtforms.FileField('Image file',validators = [DataRequired()])



class TagField(wtforms.StringField):
    def _value(self):
        if self.data:
            return ','.join([tag.name for tag in self.data])
        return ''

    def get_tags_from_string(self, tag_string):
        raw_tags = tag_string.split(',')
        tag_names = [name.strip() for name in raw_tags if name.strip()]
        existing_tags = Tag.query.filter(Tag.name.in_(tag_names))
        new_names = set(tag_names)- set([tag.name for tag in existing_tags])
        new_tags = [Tag(name = name) for name in new_names]
        return new_tags + list(existing_tags)

    def process_formdata(self, valuelist):
        if valuelist:
            self.data = self.get_tags_from_string(valuelist[0])
        else:
            self.data=[]



class EntryForm(wtforms.Form):
    title = wtforms.StringField('Title', validators = [DataRequired()])
    body = wtforms.TextAreaField('Body', validators = [DataRequired()])
    status = wtforms.SelectField('Entry Status', choices=((1,'POST'),
    (0,'DRAFT')), coerce=int)
    tags = TagField('Tags', description='Separate multiple tags with commas.')
    def save_entry(self, entry):
        self.populate_obj(entry)
        entry.generator_slug()
        return entry

entries/blueprint.py
from app import app, db
from flask import Blueprint, flash, render_template, request, redirect, url_for, g
from models import Entry,Tag,entry_tags,User
from helper import object_list
from forms import EntryForm, ImageForm
import os
from flask_login import login_required
from werkzeug import secure_filename

entries = Blueprint('entries', __name__, template_folder = 'templates')

def get_entry_or_404(slug, author = None):
    query = Entry.query.filter( Entry.slug == slug)
    if author:
        query = query.filter(Entry.author == author)
    else:
        query = filter_status_by_user(query)
    return query.first_or_404()

def filter_status_by_user(query):
    if not g.user.is_authenticated:
        query = query.filter(Entry.status == Entry.public)
    else:
        query = query.filter((Entry.status == Entry.public) |((Entry.author == g.user) & (Entry.status != Entry.eleted)))
    return query



@entries.route('/image-upload/', methods = ['GET','POST'])
@login_required
def image_upload():
    if request.method == 'POST':
        form = ImageForm(request.form)
        if form.validate():
            image_file = request.files['file']
            filename = os.path.join(app.config['IMAGES_DIR'], secure_filename(image_file.filename))
            image_file.save(filename)
            flash('Saved %s' %os.path.basename(filename),'success')
            return redirect(url_for('entries.index'))
    else:
            form = ImageForm()
    return render_template('entries/image_upload.html', form = form )



@entries.route('/')
@login_required
def index():
    entries = Entry.query.order_by(Entry.created_timestamp.desc()).filter(Entry.status!='2')
    return entry_list('entries/index.html',entries)

@entries.route('/create/', methods = ['GET','POST'])
@login_required
def create():
    form = EntryForm()
    if request.method == 'POST':
        form = EntryForm(request.form)
        if form.validate():
            entry = form.save_entry(Entry(author = g.user))
            db.session.add(entry)
            db.session.commit()
            flash('Blog: %s ,Created! ' %entry.title, 'success')
            return redirect(url_for('entries.detail', slug = entry.slug))
        else:
            form = EntryForm()
    return render_template('entries/create.html',form = form)



@entries.route('/<slug>/edit/', methods =['GET','POST'])
@login_required
def edit(slug):
    entry = get_entry_or_404(slug, g.user)
    if request.method == 'POST':
        form = EntryForm(request.form, obj=entry)
        if form.validate():
            entry = form.save_entry(entry)
            db.session.add(entry)
            db.session.commit()
            flash('Blog: %s ,Edited! ' %entry.title, 'success')
            return redirect(url_for('entries.detail', slug = entry.slug))
    else:
        form = EntryForm(obj = entry)
        return render_template('entries/edit.html', entry = entry, form = form)


@entries.route('/<slug>/delete/', methods = ['GET', 'POST'])
@login_required
def delete(slug):
    entry = get_entry_or_404(slug, g.user)
    if request.method == 'POST':
        entry.status = 2
        db.session.add(entry)
        db.session.commit()
        flash('Blog: %s ,Deleted! ' %entry.title, 'success')
        return redirect(url_for('entries.index'))
    return render_template('entries/delete.html',entry = entry )

@entries.route('/tags/')
def tag_index():
    tags = Tag.query.join(entry_tags)
    return entry_list('entries/tag_index.html',tags)

@entries.route('/tags/<slug>')
def tag_detail(slug):
    tag = Tag.query.order_by(Tag.name).filter(Tag.slug == slug).first_or_404()
    entries = tag.entries.order_by(Entry.created_timestamp.desc())
    return object_list('entries/tag_detail.html', entries,name = tag.name)

@entries.route('/<slug>')
def detail(slug):
    entry = Entry.query.filter(Entry.slug == slug).first_or_404()
    username = User.query.filter(Entry.id == entry.id, Entry.author_id==User.id).all()[0].name
    return render_template('entries/detail.html', entry = entry, username = username)

def entry_list(template, query, **context):
    search = request.args.get('q')
    if search:
        query=query.filter(Entry.body.contains(search) | (Entry.title.contains(search)))
    return object_list(template, query,**context)

entries/templates/entries/base_entries.html
{% extends "base.html" %}
{% block sidebar %}
<div class="col-md-3">
<form class="form-inline well" method="get" role="form">
<div class="input-group">
<input class="form-control input-xs" name="q"
placeholder="Search..." value="{{ request.args.get('q', '') }}" />
<span class="input-group-btn">
<button class="btn btn-default" type="submit">Go</button>
</span>
</div>
</form>
</div>
{% endblock %}
{% block content %}
{% include "includes/list.html" %}
{% include "includes/page_links.html" %}
{% endblock %}

entries/templates/entries/create.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}
{% block title %}Create new entry{% endblock %}
{% block content_title %}Create new entry{% endblock %}
{% block content %}
<form action="{{ url_for('entries.create') }}" class="form form-horizontal" method="post">
{% for field in form %}
{{ form_field(field) }}
{% endfor %}
<div class="form-group">
<div class="col-sm-offset-3 col-sm-9">
<button type="submit" class="btn btn-
default">Create</button>
<a class="btn" href="{{ url_for('entries.index')
}}">Cancel</a>
</div>
</div>
</form>
{% endblock %}

entries/templates/entries/delete.html
{% extends "base.html" %}
{% block title %}{{ entry.title }}{% endblock %}
{% block content_title %}{{ entry.title }}{% endblock %}
{% block content %}
<form action="{{ url_for('entries.delete', slug = entry.slug) }}" method="post">
<fieldset>
<legend>Delete this entry?</legend>
<button class="btn btn-danger" type="submit">Delete</button>
<a class="btn" href="{{ url_for('entries.detail', slug=entry.slug) }}">Cancel</a>
</fieldset>
</form>
{% endblock %}

entries/templates/entries/detail.html
{% extends "base.html" %}
{% block title %}{{ entry.title }}- {% endblock %}
{% block content_title %}{{ entry.title }}


{% endblock %}
{% block sidebar %}
<div class="col-md-3">
 <ul class="well nav nav-list">
   <li><h4>Tags</h4></li>
{% for tag in entry.tags %}
    <li><a href="{{ url_for('entries.tag_detail', slug=tag.slug)}}">{{ tag.name }}</a></li>
{% endfor %}
</div>
   </ul>
{% endblock %}
{% block content %}
<p>{{ entry.body }}</p>
<p>Published By- {{username}} [ {{ entry.created_timestamp.strftime('%d/%m/%Y')}} ]</p>
{%if g.user == entry.author %}
<a href="{{ url_for('entries.edit', slug = entry.slug) }}"><button class ="btn btn-primary">Edit</button></a>
<a href="{{ url_for('entries.delete', slug = entry.slug) }}"><button class ="btn btn-primary">Delete</button></a>
{%endif%}
{%endblock%}

entries/templates/entries/edit.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}
{% block title %}Edit {{ entry.title }}{% endblock %}
{% block content_title %}Edit {{ entry.title }}{% endblock %}
{% block content %}
<form action="{{ url_for('entries.edit', slug=entry.slug) }}" class="form form-horizontal" method="post">
{% for field in form %}
{{ form_field(field) }}
{% endfor %}
<div class="form-group">
<div class="col-sm-offset-3 col-sm-9">
<button type="submit" class="btn btn-default">Save</button>
<a class="btn" href="{{ url_for('entries.detail', slug = entry.slug) }}">Cancel</a>
</div>
</div>
</form>
{% endblock %}

entries/templates/entries/image_upload.html
{% extends "base.html" %}
{% from "macros/form_field.html" import form_field %}
{% block title %}Upload an image{% endblock %}
{% block content_title %}Upload an image{% endblock %}
{% block content %}
<form action="{{ url_for('entries.image_upload') }}"
enctype="multipart/form-data" method="POST">
{% for field in form %}
{{ form_field(field) }}
{% endfor %}
<div class="form-group">
<div class="col-sm-offset-3 col-sm-9">
<button type="submit" class="btn btn-default">Upload</button>
<a class="btn" href="{{ url_for('homepage')}}">Cancel</a>
</div>
</div>
</form>
{% endblock %}

entries/templates/entries/index.html
{% extends "entries/base_entries.html" %}
{% block title %}Entries- {% endblock %}
{% block content_title %}Blogs{% endblock %}

entries/templates/entries/tag_detail.html
{% extends "entries/base_entries.html" %}
{% block title %}Tags{% endblock %}
{% block content_title %}Tags{% endblock %}

entries/templates/entries/tag_index.html
{% extends "base.html" %}
{% block title %}Tags{% endblock %}
{% block content_title %}Tags{% endblock %}
{% block content %}
<ul>
{% for tag in object_list.items %}
<li><a href="{{ url_for('entries.tag_detail', slug=tag.slug)
}}">{{ tag.name }}</a></li>
{% endfor %}
</ul>
{% endblock %}